# Creating rate limit policy
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-policy
  namespace: apps-cafe
spec:
  rateLimit:
    rate: 3r/s
    key: ${binary_remote_addr}
    zoneSize: 10M
    rejectCode: 429
---    
# Creating VirtualServer on Nginx Plus KIC
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe-vs
  namespace: apps-cafe
spec:
  host: cafe.f5demo.io
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea-post
    service: tea-post-svc
    port: 80
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee-v1
    service: coffee-v1-svc
    port: 80
  - name: coffee-v2
    service: coffee-v2-svc
    port: 80
  routes:
  - path: /tea
    policies:
    - name: rate-limit-policy
    matches:
    - conditions:
      - variable: $request_method
        value: POST
      action:
        pass: tea-post
    action:
      pass: tea
  - path: /coffee
    matches:
    - conditions:
      - cookie: version
        value: v2
      action:
        pass: coffee-v2
    action:
      pass: coffee-v1
  - path: /split
    splits:
    - weight: 70
      action:
        pass: coffee-v1
    - weight: 30
      action:
        pass: coffee-v2
---
# Creating TLS profile for CIS VirtualServer
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: bridging-tls-profile-npl
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    # Define clientssl profile
    clientSSL: cafe-secret
    clientSSLParams:
      profileReference: secret
    # Define serverssl profile    
    serverSSL: /Common/serverssl-insecure-compatible
    serverSSLParams:
      profileReference: bigip
      # serverName: "cafe.f5demo.io" --> currently not supported, ETA available on CIS 2.20.4 (https://github.com/F5Networks/k8s-bigip-ctlr/issues/4001)
    reference: hybrid
  hosts:
  - "cafe.f5demo.io"
---
# Creating CIS VirtualServer 443
apiVersion: "cis.f5.com/v1"
kind: VirtualServer 
metadata:
  name: cis-vs-cafe-443-npl
  namespace: nginx-ingress
  labels: 
    f5cr: "true"
spec:
  host: "cafe.f5demo.io"
  tlsProfileName: bridging-tls-profile-npl
  virtualServerName: cis-vs-cafe-443-npl
  iRules:
  - /Common/irules-sni
  virtualServerAddress: "10.1.1.14" #--> update as needed
  virtualServerHTTPPort: 443 #--> update as needed
  persistenceProfile: "cookie"
  pools:
  - path: /
    service: svc-nginx-ingress-npl
    servicePort: 443 #--> adjust to match targetPort of the service
    loadBalancingMethod: fastest-node
    monitor:
      type: http
      send: "GET /"
      recv: ""
      interval: 5
      timeout: 16
---
# Creating CIS VirtualServer 80 redirect
apiVersion: "cis.f5.com/v1"
kind: VirtualServer 
metadata:
  name: cis-vs-cafe-80-npl
  namespace: nginx-ingress
  labels: 
    f5cr: "true"
spec:
  virtualServerName: cis-vs-cafe-80-redirect-npl
  iRules:
  - /Common/_sys_https_redirect
  virtualServerAddress: "10.1.1.14" #--> update as needed
  virtualServerHTTPPort: 80 #--> update as needed