apiVersion: v1
kind: Service
metadata:
  name: svc-nplus-live-dash
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30880
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nplus-live-dash
  namespace: nginx-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress